
   
on: [push]
name: Linux_Container_Workflow

env:
  IMAGE_NAME: YourAlias
  
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REPOSITORY }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REPOSITORY }}/${{ env.IMAGE_NAME}}  -f ./Dockerfile
            docker push ${{ secrets.REPOSITORY }}/${{ env.IMAGE_NAME}}
